export const {
  POSTGRES_HOST,
  POSTGRES_PORT,
  POSTGRES_USERNAME,
  POSTGRES_PASSWORD,
  POSTGRES_DATABASE,
  NODE_ENV,
  PRODUCT_MICROSERVICE_URL,
  PRODUCT_PROPERTY_MICROSERVICE_URL,
  PROPERTY_MICROSERVICE_URL,
  PROPERTY_CATEGORY_MICROSERVICE_URL,
  CATEGORY_MICROSERVICE_URL,
} = process.env;
